### ISSUE TITLE
Hangman: Spielregeln Command

### ISSUE THREAD

**Issue by ThomasWeis** [SophieBartmann/Faust-Bot#105]
Das Spielregeln Kommando sollte nur per Query funktionieren, um Spam im Channel zu vermeiden. Für .spielregeln könnte man im Channel einen einfachen Hinweis geben wie "Query an den Bot .spielregeln, um die Regeln für Hangman anzuzeigen."

**Comment by SophieBartmann** [comment]
done:)
        if data['channel'] == connection.details.get_channel():
            connection.send_back("Spielregeln bitte im Query abfragen")
            return
