### ISSUE TITLE
Hangman: nicht gelöstes Wort

### ISSUE THREAD

**Issue by ThomasWeis** [SophieBartmann/Faust-Bot#106]
Wenn ein Wort nicht erraten wird, hat derjenige, von dem das Wort ist, gewonnen und müsste Punkte kriegen.

**Comment by SophieBartmann** [comment]
Tut er bereits, ist da irgendeine schwachstelle die ich nicht gesehen habe? Konkrete Situation am liebsten. Oder soll er mehr Punkte bekommen? Derzeit sind es 5.

**Comment by SophieBartmann** [comment]
Ok 11 Punkte für den steller des Wortes wnen nicht gelöst wird:)
