### ISSUE TITLE
Bot reacts on "JOIN" command in normal messages

### ISSUE THREAD

**Issue by niansa** [SophieBartmann/Faust-Bot#42]
If a user send a message which is including a JOIN command (example: <nick123> blablabla :nick!ident@host JOIN #channel blablabla) then the bot interprete it like the server has send the JOIN command and adds the user to the nicklist. I'm not sure if the bot really reacted to JOIN command, the PRIVMSG command is also possible, my message which was bad interpreted by the bot included one PRIVMSG and one JOIN command.

**Comment by ravotd** [comment]
issue duplicates #50

**Comment by niansa** [comment]
Every single time I reread this commits description I find more typos. Wow.
