### ISSUE TITLE
Feature Request: Minigame

### ISSUE THREAD

**Issue by derfalx** [SophieBartmann/Faust-Bot#49]
A nice feature would be some mini game. This could be played between users or against the bot.

Suggestions yet are:

- Hangman 
  Maybe based on the glossary module
- Blackjack
- Battleship 
  But isn't easy to integrate into the IRC
- Duck Hunt

**Comment by SophieBartmann** [comment]
Hangman is implemented

**Comment by SophieBartmann** [comment]
Could you explain the rules of black jack(espacially how it should be implemented)

**Comment by SophieBartmann** [comment]
Duck hunt is now implemented
